add logout button to base.html
AlexandraPoturaeva/ChefList_web pull request #33
Opened 2023-07-10 13:48 UTC by unickname3

Добавил логику замены кнопок Зарегистрироваться и Войти на Выйти для зарегистрированных пользователей.

2023-07-11 06:03 UTC, krepysh requested changes

2023-07-11 06:03 UTC, krepysh commented on webapp/__init__.py
> +        return render_template("index.html", unauthorized=current_user.is_anonymous)
Это не нужно передавать снаружи. Ты можешь внутри шаблона обращаться к current_user
[example](https://flask-login.readthedocs.io/en/latest/#:~:text=It%E2%80%99s%20that%20simple.%20You%20can%20then%20access%20the%20logged%2Din%20user%20with%20the%20current_user%20proxy%2C%20which%20is%20available%20in%20every%20template%3A)

2023-07-11 06:03 UTC, krepysh commented on webapp/__init__.py
> +            unauthorized=current_user.is_anonymous,
аналогично

2023-07-11 06:04 UTC, krepysh requested changes
Во всех местах убери передачу в шаблон unauthorised

2023-07-11 18:37 UTC, unickname3 commented on webapp/__init__.py
> +        return render_template("index.html", unauthorized=current_user.is_anonymous)
Не знал. Исправил.

2023-07-14 15:40 UTC, krepysh approved these changes

2023-07-14 18:47 UTC, merged